# Generated by Django 3.2.5 on 2021-08-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210731_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtoken',
            name='user_email',
            field=models.CharField(default='', max_length=255),
        ),
    ]
